### ISSUE TITLE
After Effects CC 2014 render queue failed to export

### ISSUE THREAD

**Issue by marijneken** [MOXfiles/AdobeMOX#1]
1. Plugin version 1.0a1 for After Effects
2. After Effects CC 2014 (2014.2 Release, version 13.2.0.4), OS X 10.10.3 (14D136)
3. Settings at default: RGB, Millions of Colors, 1920x1080, 24fps, no audio
4. Created a fresh project, with one 5 second comp and a layer of text. Added it to the render queue and used the settings described above. Pressed render and got this error:

After Effects error: strange situation [0/115]. ( 26 :: 142 )

![ae_cc_2014](https://cloud.githubusercontent.com/assets/928998/8145302/903d5e7c-11fa-11e5-9511-a8c5d8b0ede1.png)

**Comment by fnordware** [comment]
Yep, I've seen this one from time to time myself. Not the most helpful error! Working to get to the bottom of it.

**Comment by fnordware** [comment]
Could you try with Alpha 2 and let me know if you're still getting the problem?

**Comment by marijneken** [comment]
Just tried it and got the same exact error. Tried multiple times. Same error every time.

**Comment by marijneken** [comment]
Alpha 3 has seemed to have fixed this issue. Now successfully created NOX file that I could read back into After Effects as well... well done!
